services:
  postgres: 
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=simplebank
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/simplebank?sslmode=disable
    volumes:
      - .:/app
    command: go run main.go

volumes:
  postgres: